server:
  port: 8081
spring:
  rabbitmq:
    addresses: rabbitmq.hm.ans.gov.br:5672
    username: tashmahall
    password: tashmahall
    virtual-host: desenv
    cache:
      connection:
        mode: connection
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
debug: false