spring:
    cache:
      connection:
        mode: connection
ans:  snirabbitmq:    connection-timeout: 15000
    consume-timeout: 15000
    reply-timeout: 15000
    host: rabbitmqfila.hm.ans.gov.br
    port: 443
    rabbitmq-password: guest
    rabbitmq-username: guest
    sni-host-name: rabbitmqfila.hm.ans.gov.br
    ssl-algorithm: TLSv1.2
    trust-store-location: truststore.jks
    trust-store-password: changeit
    trust-store-type: jks
    virtual-host: desenv

logging:  level:    root: DEBUG 
    
