spring:
  rabbitmq:
    addresses: localhost:5671,localhost:5672,localhost:5673
    username: tashmahall
    password: tashmahall
    virtual-host: desenv
    cache:
      connection:
        mode: connection
      
debug: true